import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.List;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
import ocgr.*;

@SuppressWarnings("serial")
public class ViewByCategory extends HttpServlet {
	public void doGet 	(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
		response.setContentType("text/html; charset=ISO-8859-7");
		PrintWriter out = new PrintWriter(response.getWriter(), true);
		HttpSession session = request.getSession(true);
		try {
			session.getAttribute("user-object");
		} catch(Exception e) {
			request.setAttribute("message", e.getMessage());
		}
		String userType = null;
		String username = null;
		Client client = null;
		Vendor vendor = null;
		if (session.getAttribute("user-object")!= null){
			try {
				userType = (String) session.getAttribute("user-type");
			} catch (Exception e) {
				request.setAttribute("message", e.getMessage());
			}
			if (userType.equals("client")) {
				client = (Client)session.getAttribute("user-object");
				username = client.getFullname();
			} else if (userType.equals("vendor")) {
				vendor = (Vendor)session.getAttribute("user-object");
				username = vendor.getFullname();
			} else {
				throw new ServletException("Invalid user object");
			}
		} else {
			request.setAttribute("message", "Login is necessary in order to proceed");
			response.sendRedirect("http://ism.dmst.aueb.gr/ismgroup42/login.jsp");		
		}

		String category_id = request.getParameter("id");
		CategoryDAO cdao = new CategoryDAO();
		Category category = null;
		try {
			category = cdao.getCategorybyId(category_id);
		} catch (Exception e1) {
			e1.printStackTrace();
		}
		ProductDAO pdao = new ProductDAO();
		List<Product> products = new ArrayList<Product>();
		try {
			products = pdao.getProductByCategory(category);
		} catch (Exception e) {
			e.printStackTrace();
		}

		try {
			out.println("<!doctype html>");
			out.println("<!--[if lt IE 7]>      <html class='no-js lt-ie9 lt-ie8 lt-ie7' lang=''> <![endif]-->");
			out.println("<!--[if IE 7]>         <html class='no-js lt-ie9 lt-ie8' lang=''> <![endif]-->");
			out.println("<!--[if IE 8]>         <html class='no-js lt-ie9' lang=''> <![endif]-->");
			out.println("<!--[if gt IE 8]><!-->");
			out.println("<html class='no-js' lang='en-US'>");
			out.println("<!--<![endif]-->");
			out.println("");
			out.println("<head>");
			out.println("	<meta charset='utf-8'>");
			out.println("	<meta http-equiv='X-UA-Compatible' content='IE=edge'>");
			out.println("	<title>Open Commerce | "+ category.getName() +"</title>");
			out.println("	<meta name='description' content='An online marketplace for professional and industrial use'>");
			out.println("	<meta name='keywords' content='e-commerce, online store, order, professional, industry, tools, machinery' />");
			out.println("	<meta name='author' content='Codrops, ismgroup42' />");
			out.println("	<meta name='viewport' content='width=device-width, initial-scale=1'>");
			out.println("	<!-- favicon generated by http://realfavicongenerator.net/ -->");
			out.println("	<link rel='apple-touch-icon' sizes='57x57' href='img/favicon/apple-touch-icon-57x57.png'>");
			out.println("	<link rel='apple-touch-icon' sizes='60x60' href='img/favicon/apple-touch-icon-60x60.png'>");
			out.println("	<link rel='apple-touch-icon' sizes='72x72' href='img/favicon/apple-touch-icon-72x72.png'>");
			out.println("	<link rel='apple-touch-icon' sizes='76x76' href='img/favicon/apple-touch-icon-76x76.png'>");
			out.println("	<link rel='apple-touch-icon' sizes='114x114' href='img/favicon/apple-touch-icon-114x114.png'>");
			out.println("	<link rel='apple-touch-icon' sizes='120x120' href='img/favicon/apple-touch-icon-120x120.png'>");
			out.println("	<link rel='apple-touch-icon' sizes='144x144' href='img/favicon/apple-touch-icon-144x144.png'>");
			out.println("	<link rel='apple-touch-icon' sizes='152x152' href='img/favicon/apple-touch-icon-152x152.png'>");
			out.println("	<link rel='apple-touch-icon' sizes='180x180' href='img/favicon/apple-touch-icon-180x180.png'>");
			out.println("	<link rel='icon' type='image/png' href='img/favicon/favicon-32x32.png' sizes='32x32'>");
			out.println("	<link rel='icon' type='image/png' href='img/favicon/favicon-194x194.png' sizes='194x194'>");
			out.println("	<link rel='icon' type='image/png' href='img/favicon/favicon-96x96.png' sizes='96x96'>");
			out.println("	<link rel='icon' type='image/png' href='img/favicon/android-chrome-192x192.png' sizes='192x192'>");
			out.println("	<link rel='icon' type='image/png' href='img/favicon/favicon-16x16.png' sizes='16x16'>");
			out.println("	<link rel='manifest' href='img/favicon/manifest.json'>");
			out.println("	<link rel='mask-icon' href='img/favicon/safari-pinned-tab.svg' color='#5bbad5'>");
			out.println("	<link rel='shortcut icon' href='img/favicon/favicon.ico'>");
			out.println("	<meta name='msapplication-TileColor' content='#66e0e5'>");
			out.println("	<meta name='msapplication-TileImage' content='img/favicon/mstile-144x144.png'>");
			out.println("	<meta name='msapplication-config' content='img/favicon/browserconfig.xml'>");
			out.println("	<meta name='theme-color' content='#ffffff'>");
			out.println("	<!-- end favicon links -->");
			out.println("	<link rel='stylesheet' href='css/bootstrap.min.css' />");
			out.println("	<link rel='stylesheet' href='css/normalize.min.css'>");
			out.println("	<link rel='stylesheet' href='css/animate.min.css'>");
			out.println("	<link rel='stylesheet' href='css/flickity.min.css'>");
			out.println("	<link rel='stylesheet' href='css/styles.css'>");
			out.println("	<link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css'>");
			out.println("</head>");
			out.println("");
			out.println("<body>");
			out.println("<!--[if lt IE 8]>");
			out.println("	<p class='browserupgrade'>You are using an <strong>outdated</strong> browser. Please <a href='http://browsehappy.com/'>upgrade your browser</a> to improve your experience.</p>");
			out.println("	<![endif]-->");
			out.println("<div class='container-fluid'>");
			out.println("		<div class='row'>");
			out.println("			<div class='header-nav-wrapper'>");
			out.println("				<div class='logo'>");
			out.println("					<a href='index.html'><img src='img/synthetica-logo.png' alt='Logo Goes Here'></a>");
			out.println("				</div>");
			out.println("				<div class='primary-nav-wrapper'>");
			out.println("					<nav>");
			out.println("						<ul class='primary-nav'>");
			out.println("							<li><a href='index.html'>Home</a></li>");
			out.println("							<li><a href='categories.html'>Browse</a></li>");
			out.println("						</ul>");
			out.println("					</nav>");
			out.println("					<div class='secondary-nav-wrapper'>");
			out.println("						<ul class='secondary-nav'>");
			if (session.getAttribute("user-object") == null){
				out.println("							<li class='subscribe'><a href='login.html'>Log In</a></li>");
			} else {
			out.println("							<li class='subscribe dropdown'>");
			out.println("								<a class='dropdown-toggle' data-toggle='dropdown' href='#' aria-haspopup='true'>"+ username +"<span class='caret'></span></a>");
			out.println("								<div class='dropdown-menu'>");
			out.println("									<ul class='dropdown-menu'>");
			out.println("										<li><a class='dropdown-item' href='dashboard.jsp'>Dashboard</a>");
			out.println("										<li><a class='dropdown-item' href='logout.jsp'>Logout</a></li>");
			out.println("									</ul>");
			out.println("								</div>	");
			out.println("							</li>");
			}
			out.println("							<li class='search'><a href='#search' class='show-search'><i class='fa fa-search'></i></a></li>");
			out.println("						</ul>");
			out.println("					</div>");
			out.println("					<div class='search-wrapper'>");
			out.println("						<ul class='search'>");
			out.println("							<li>");
			out.println("								<input type='text' id='search-input' placeholder='Start typing then hit enter to search'>");
			out.println("								<span><a href='advanced_search.html'>Advanced search</a></span>");
			out.println("							</li>");
			out.println("							<li>");
			out.println("								<a href='#' class='hide-search'><i class='fa fa-close'></i></a>");
			out.println("							</li>");
			out.println("						</ul>");
			out.println("					</div>");
			out.println("				</div>");
			out.println("				<div class='navicon'>");
			out.println("					<a class='nav-toggle' href='#'><span></span></a>");
			out.println("				</div>");
			out.println("			</div>");
			out.println("		</div>");
			out.println("	</div>");
			out.println("	<!-- Articles -->");
			out.println("	<section class='latest-articles has-padding alternate-bg' id='articles'>");
			out.println("		<div class='container'>");
			out.println("			<div class='row'>");
			out.println("				<div class='col-md-4 col-sm-4'>");
			out.println("					<h4>Browse: <small>"+ category.getName() +"</small></h4>");
			out.println("				</div>");
			out.println("				<div class='col-md-8 col-sm-8 sort'>");
			out.println("					<h5>Sort by</h5>");
			out.println("					<select name='article-sort' id='inputArticle-Sort' class=''>");
			out.println("						<option value=''>Popularity</option>");
			out.println("						<option value=''>Price per Piece(Ascending)</option>");
			out.println("						<option value=''>Price per Piece(Descending)</option>");
			out.println("						<option value=''>Rating</option>");
			out.println("					</select>");
			out.println("				</div>");
			out.println("			</div>");
			int counter = 0;
			int rowcheck = 0;
			for (Product product : products) {
				counter++;
				if (counter == 1 && rowcheck > 0) {
					out.println("			<div class='row has-top-margin'>");
					out.println("				<div class='col-md-4'>");
					out.println("					<article class='article-post'>");
					out.println("						<a href='/ViewProduct?id="+product.getId()+"'>");
					out.println("							<div class='article-image has-overlay' style='background-image: url(img/article-01.jpg)'>");
					out.println("							</div>");
					out.println("							<figure>");
					out.println("								<figcaption>");
					out.println("									<h2>Product 1</h2>");
					out.println("									<p><em>Product Description:</em> "+product.getDescription()+"</p>");
					out.println("								</figcaption>");
					out.println("							</figure>");
					out.println("						</a>");
					out.println("						<ul class='article-footer'>");
					out.println("							<li class='article-category'>");
					out.println("								<a href='#'>"+category.getName()+"</a>");
					out.println("							</li>");
					out.println("							");
					out.println("							<li class='article-comments'>");
					out.println("								<span><i class='fa fa-star'></i>"+pdao.getAverageRatings(product)+"&emsp;</span>");
					out.println("							</li>");
					out.println("						</ul>");
					out.println("					</article>");
					out.println("				</div>");

				}else if (counter == 1) {
					out.println("			<div class='row'>");
					out.println("				<div class='col-md-4'>");
					out.println("					<article class='article-post'>");
					out.println("						<a href='/ViewProduct?id="+product.getId()+"'>");
					out.println("							<div class='article-image has-overlay' style='background-image: url(img/article-01.jpg)'>");
					out.println("							</div>");
					out.println("							<figure>");
					out.println("								<figcaption>");
					out.println("									<h2>Product 1</h2>");
					out.println("									<p><em>Product Description:</em> "+product.getDescription()+"</p>");
					out.println("								</figcaption>");
					out.println("							</figure>");
					out.println("						</a>");
					out.println("						<ul class='article-footer'>");
					out.println("							<li class='article-category'>");
					out.println("								<a href='#'>"+category.getName()+"</a>");
					out.println("							</li>");
					out.println("							");
					out.println("							<li class='article-comments'>");
					out.println("								<span><i class='fa fa-star'></i>"+pdao.getAverageRatings(product)+"&emsp;</span>");
					out.println("							</li>");
					out.println("						</ul>");
					out.println("					</article>");
					out.println("				</div>");

				} else {
					out.println("				<div class='col-md-4'>");
					out.println("					<article class='article-post'>");
					out.println("						<a href='/ViewProduct?id="+product.getId()+"'>");
					out.println("							<div class='article-image has-overlay' style='background-image: url(img/article-01.jpg)'>");
					out.println("							</div>");
					out.println("							<figure>");
					out.println("								<figcaption>");
					out.println("									<h2>Product 1</h2>");
					out.println("									<p><em>Product Description:</em> "+product.getDescription()+"</p>");
					out.println("								</figcaption>");
					out.println("							</figure>");
					out.println("						</a>");
					out.println("						<ul class='article-footer'>");
					out.println("							<li class='article-category'>");
					out.println("								<a href='#'>"+category.getName()+"</a>");
					out.println("							</li>");
					out.println("							");
					out.println("							<li class='article-comments'>");
					out.println("								<span><i class='fa fa-star'></i>"+pdao.getAverageRatings(product)+"&emsp;</span>");
					out.println("							</li>");
					out.println("						</ul>");
					out.println("					</article>");
					out.println("				</div>");
				}
				if (counter == 3) {
					out.println("			</div>");
					counter = 0;
					rowcheck++;
				}
				out.println("	<!-- SECTION: Footer -->");
				out.println("	<footer class='has-padding footer-bg'>");
				out.println("		<div class='container'>");
				out.println("			<div class='row'>");
				out.println("				<div class='col-md-4 footer-branding wp5'>");
				out.println("					<img class='footer-branding-logo' src='img/synthetica-logo.png' alt='Synthetica freebie html5 css3 template logo'>");
				out.println("				</div>");
				out.println("				<div class='col-md-4 footer-branding wp5'>");
				out.println("					<img class='footer-branding-logo' src='img/ismgroup42.png' alt='ismlogo'>");
				out.println("				</div>");
				out.println("				<div class='col-md-4 footer-branding wp5'>");
				out.println("					<img class='footer-branding-logo' src='img/DMST.png' alt='dmstl'>");
				out.println("				</div>");
				out.println("			</div>");
				out.println("			<div class='row'>");
				out.println("				<div class='col-md-4 footer-branding wp5 animated fadeIn'>");
				out.println("					<p>Opencommerce.gr was created using the theme Synthetica, generously provided by <a href='http://peterfinlan.com/'><em>Peter Finlan</em></a> for <a href='https://tympanus.net/codrops/'><em>codrops</em></a>. Back-end coding and modification by <a href='#'><em>ismGroup42</em></a>.</p>");
				out.println("				</div>");
				out.println("			</div>");
				out.println("			<div class='row'>");
				out.println("				<div class='col-md-12 footer-nav'>");
				out.println("					<ul class='footer-primary-nav'>");
				out.println("						<li><a href='index.html'>Home</a></li>");
				out.println("						<li><a href='categories.html'>Browse</a></li>");
				out.println("						<li><a href='advanced_search.html'>Advanced Search</a></li>");
				out.println("						<li><a href='dashboard.html'>Dashboard</a></li>");
				out.println("					</ul>");
				out.println("					<ul class='footer-share'>");
				out.println("						<li><a href='http://tympanus.net/codrops/licensing/'>Licence</a></li>");
				out.println("						<li><a href='#' class='share-trigger'><i class='fa fa-share'></i>Share</a></li>");
				out.println("					</ul>");
				out.println("					<div class='share-dropdown'>");
				out.println("						<ul>");
				out.println("							<li><a href='#' class='share-twitter'><i class='fa fa-twitter'></i></a></li>");
				out.println("							<li><a href='#' class='share-facebook'><i class='fa fa-facebook'></i></a></li>");
				out.println("							<li><a href='#' class='share-linkedin'><i class='fa fa-linkedin'></i></a></li>");
				out.println("						</ul>");
				out.println("					</div>");
				out.println("					<ul class='footer-secondary-nav'>");
				out.println("						<li><p>© Copyright <a href='#'><em> ismGroup42</em></a>. All rights reserved | <a href='#'><em>Terms Of Use</em></a> | <a href='#'><em>Contact</em></a></p></li>");
				out.println("					</ul>");
				out.println("				</div>");
				out.println("			</div>");
				out.println("		</div>");
				out.println("	</footer>");
				out.println("	<!-- END SECTION: Footer -->");
				out.println("	<!-- JS CDNs -->");
				out.println("	<script src='http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js'></script>");
				out.println("	<script src='http://ajax.googleapis.com/ajax/libs/jqueryui/1.11.0/jquery-ui.min.js'></script>");
				out.println("	<script src='http://vjs.zencdn.net/5.4.6/video.min.js'></script>");
				out.println("	<!-- jQuery local fallback -->");
				out.println("	<script>");
				out.println("	window.jQuery || document.write('<script src='js/min/jquery-1.11.2.min.js'></script>')");
				out.println("	</script>");
				out.println("	<!-- JS Locals -->");
				out.println("	<script src='js/min/bootstrap.min.js'></script>");
				out.println("	<script src='js/min/modernizr-2.8.3-respond-1.4.2.min.js'></script>");
				out.println("	<script src='js/min/retina.min.js'></script>");
				out.println("	<script src='js/min/jquery.waypoints.min.js'></script>");
				out.println("	<script src='js/min/flickity.pkgd.min.js'></script>");
				out.println("	<script src='js/min/scripts-min.js'></script>");

			}

		} catch (Exception e) {
			e.printStackTrace();
			out.println("	<div class='container'>");
			out.println("		<div class='alert alert-danger' role='alert'>");
			out.println("			<p class='text-center'> Error : " + e.getMessage()+"</p>");
			out.println("		</div>");
			out.println("	</div>");
			out.println("	<!-- footer -->");
			out.println("		<footer class='navbar-inverse'>");
			out.println("			<div class='container'>");
			out.println("				<div class='row'>");
			out.println("					<div class='col-xs-12'>");
			out.println("						<p class='text-center'>&copy; Copyright 2017 by ismgroup42</p>");
			out.println("					</div>");
			out.println("				</div>");
			out.println("			</div>");
			out.println("		</footer>");
			out.println("		<!-- End footer -->");
			out.println("");
			out.println("		<!-- =================== Place all javascript at the end of the document so the pages load faster =================== -->");
			out.println("		<!-- jQuery library -->");
			out.println("		<script src='https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js'></script>");
			out.println("		<!-- Bootstrap core JavaScript -->");
			out.println("		<script src='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js' integrity='sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa' crossorigin='anonymous'></script>");
			out.println("");
			out.println("</body>");
			out.println("</html>");
		}

	}
}
