import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.math.BigDecimal;
import java.util.Set;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;
import ocgr.*;

@SuppressWarnings("serial")
public class ViewProduct extends HttpServlet {

	public void doPost 	(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {

		response.setContentType("text/html; charset=ISO-8859-7");
		PrintWriter out = new PrintWriter(response.getWriter(), true);
		HttpSession session = request.getSession(true);

		session.setAttribute("currentPage", request.getRequestURI().replace(request.getContextPath() + "/","") );

		try {
			session.getAttribute("user-object");
		} catch(Exception e) {
			request.setAttribute("message", e.getMessage());
		}
		String userType = null;
		String username = null;
		Client client = null;
		Vendor vendor = null;
		if (session.getAttribute("user-object")!= null){
			try {
				userType = (String) session.getAttribute("user-type");
			} catch (Exception e) {
				request.setAttribute("message", e.getMessage());
			}
			if (userType.equals("client")) {
				client = (Client)session.getAttribute("user-object");
				username = client.getFullname();
			} else if (userType.equals("vendor")) {
				vendor = (Vendor)session.getAttribute("user-object");
				username = vendor.getFullname();
			} else {
				throw new ServletException("Invalid user object");
			}
		} else {
			Set<String> pages = new HashSet<String>();
			pages.add("dashboard.jsp");
			pages.add("order.jsp");
			pages.add("checkout.jsp");
			pages.add("submitProduct.jsp");
			if( pages.contains(request.getRequestURI().replace(request.getContextPath() + "/","")) ) {
				request.setAttribute("message", "Login is necessary in order to proceed");
				response.sendRedirect("http://ism.dmst.aueb.gr/ismgroup42/login.jsp");
			}
		}

		String product_id = request.getParameter("prod_id");
		session.setAttribute("prod_id", product_id);

		ProductDAO pdao = new ProductDAO();
		Product product = null;
		try {
			product = pdao.getProductById(product_id);
		} catch (Exception e) {
			e.printStackTrace();
		}

		String category_id = null;
		try {
			category_id = product.getCategory().getId();
		} catch (Exception e1) {
			e1.printStackTrace();
		}
		CategoryDAO cdao = new CategoryDAO();
		Category category = null;
		try {
			category = cdao.getCategorybyId(category_id);
		} catch (Exception e1) {
			e1.printStackTrace();
		}

		double price = 0.0;
		BigDecimal big_price = new BigDecimal(0.0);
		try {
			big_price = pdao.getPricing(product);
			price = big_price.doubleValue();
		} catch (Exception e1) {
			e1.printStackTrace();
		}

		VendorDAO vdao = new VendorDAO();
		String vendor_id = null;
		try {
			vendor_id = vdao.getVendorByProduct(product).getId();
		} catch (Exception e) {
			e.printStackTrace();
		}

		session.setAttribute("product_id", product_id);
		session.setAttribute("vendor_id", vendor_id);
		session.setAttribute("show_order", null);

		try {
			out.println("<!doctype html>");
			out.println("<!--[if lt IE 7]>      <html class='no-js lt-ie9 lt-ie8 lt-ie7' lang=''> <![endif]-->");
			out.println("<!--[if IE 7]>         <html class='no-js lt-ie9 lt-ie8' lang=''> <![endif]-->");
			out.println("<!--[if IE 8]>         <html class='no-js lt-ie9' lang=''> <![endif]-->");
			out.println("<!--[if gt IE 8]><!-->");
			out.println("<html class='no-js' lang='en-US'>");
			out.println("<!--<![endif]-->");
			out.println("");
			out.println("<head>");
			out.println("	<meta charset='utf-8'>");
			out.println("	<meta http-equiv='X-UA-Compatible' content='IE=edge'>");
			out.println("	<title>"+ product.getName() +" | Open Commerce </title>");
			out.println("	<meta name='description' content='An online marketplace for professional and industrial use'>");
			out.println("	<meta name='keywords' content='e-commerce, online store, order, professional, industry, tools, machinery' />");
			out.println("	<meta name='author' content='Codrops, ismgroup42' />");
			out.println("	<meta name='viewport' content='width=device-width, initial-scale=1'>");
			out.println("	<!-- favicon generated by http://realfavicongenerator.net/ -->");
			out.println("	<link rel='apple-touch-icon' sizes='57x57' href='img/favicon/apple-touch-icon-57x57.png'>");
			out.println("	<link rel='apple-touch-icon' sizes='60x60' href='img/favicon/apple-touch-icon-60x60.png'>");
			out.println("	<link rel='apple-touch-icon' sizes='72x72' href='img/favicon/apple-touch-icon-72x72.png'>");
			out.println("	<link rel='apple-touch-icon' sizes='76x76' href='img/favicon/apple-touch-icon-76x76.png'>");
			out.println("	<link rel='apple-touch-icon' sizes='114x114' href='img/favicon/apple-touch-icon-114x114.png'>");
			out.println("	<link rel='apple-touch-icon' sizes='120x120' href='img/favicon/apple-touch-icon-120x120.png'>");
			out.println("	<link rel='apple-touch-icon' sizes='144x144' href='img/favicon/apple-touch-icon-144x144.png'>");
			out.println("	<link rel='apple-touch-icon' sizes='152x152' href='img/favicon/apple-touch-icon-152x152.png'>");
			out.println("	<link rel='apple-touch-icon' sizes='180x180' href='img/favicon/apple-touch-icon-180x180.png'>");
			out.println("	<link rel='icon' type='image/png' href='img/favicon/favicon-32x32.png' sizes='32x32'>");
			out.println("	<link rel='icon' type='image/png' href='img/favicon/favicon-194x194.png' sizes='194x194'>");
			out.println("	<link rel='icon' type='image/png' href='img/favicon/favicon-96x96.png' sizes='96x96'>");
			out.println("	<link rel='icon' type='image/png' href='img/favicon/android-chrome-192x192.png' sizes='192x192'>");
			out.println("	<link rel='icon' type='image/png' href='img/favicon/favicon-16x16.png' sizes='16x16'>");
			out.println("	<link rel='manifest' href='img/favicon/manifest.json'>");
			out.println("	<link rel='mask-icon' href='img/favicon/safari-pinned-tab.svg' color='#5bbad5'>");
			out.println("	<link rel='shortcut icon' href='img/favicon/favicon.ico'>");
			out.println("	<meta name='msapplication-TileColor' content='#66e0e5'>");
			out.println("	<meta name='msapplication-TileImage' content='img/favicon/mstile-144x144.png'>");
			out.println("	<meta name='msapplication-config' content='img/favicon/browserconfig.xml'>");
			out.println("	<meta name='theme-color' content='#ffffff'>");
			out.println("	<!-- end favicon links -->");
			out.println("	<link rel='stylesheet' href='css/bootstrap.min.css' />");
			out.println("	<link rel='stylesheet' href='css/normalize.min.css'>");
			out.println("	<link rel='stylesheet' href='css/animate.min.css'>");
			out.println("	<link rel='stylesheet' href='css/flickity.min.css'>");
			out.println("	<link rel='stylesheet' href='css/styles.css'>");
			out.println("	<link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css'>");
			out.println("    <link href='css/star-rating.css' media='all' rel='stylesheet' type='text/css'/>");
			out.println("    <!--suppress JSUnresolvedLibraryURL -->");
			out.println("    <script src='http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js'></script>");
			out.println("    <script src='js/star-rating.js' type='text/javascript'></script>");

			out.println("</head>");
			out.println("");
			out.println("<body>");
			out.println("<!--[if lt IE 8]>");
			out.println("	<p class='browserupgrade'>You are using an <strong>outdated</strong> browser. Please <a href='http://browsehappy.com/'>upgrade your browser</a> to improve your experience.</p>");
			out.println("	<![endif]-->");
			out.println("<div class='container-fluid'>");
			out.println("		<div class='row'>");
			out.println("			<div class='header-nav-wrapper'>");
			out.println("				<div class='logo'>");
			out.println("					<a href='index.jsp'><img src='img/synthetica-logo.png' alt='Logo Goes Here'></a>");
			out.println("				</div>");
			out.println("				<div class='primary-nav-wrapper'>");
			out.println("					<nav>");
			out.println("						<ul class='primary-nav'>");
			out.println("							<li><a href='index.jsp'>Home</a></li>");
			out.println("							<li><a href='browse.jsp'>Browse</a></li>");
			out.println("						</ul>");
			out.println("					</nav>");
			out.println("					<div class='secondary-nav-wrapper'>");
			out.println("						<ul class='secondary-nav'>");
			if (session.getAttribute("user-object") == null){
				out.println("							<li class='subscribe'><a href='login.jsp'>Log In</a></li>");
			} else {
				out.println("							<li class='subscribe dropdown'>");
				out.println("								<a class='dropdown-toggle' data-toggle='dropdown' href='#' aria-haspopup='true'>"+ username +"<span class='caret'></span></a>");
				out.println("								<div class='dropdown-menu'>");
				out.println(" 									<h5>&ensp;User type:" +session.getAttribute("user-type")+"</h5>");
				out.println("									<ul class='dropdown-menu'>");
				out.println("										<li><a class='dropdown-item' href='dashboard.jsp'>Dashboard</a>");
				out.println("										<li><a class='dropdown-item' href='logout.jsp'>Logout</a></li>");
				out.println("									</ul>");
				out.println("								</div>	");
				out.println("							</li>");
			}
			out.println("							<li class='search'><a href='#search' class='show-search'><i class='fa fa-search'></i></a></li>");
			out.println("						</ul>");
			out.println("					</div>");
			out.println("					<div class='search-wrapper'>");
			out.println("						<ul class='search'>");
			out.println("							<li>");
			out.println("								<form name='simpleSearch' method='post' action='Search'>");
			out.println("								<input type='text' name='search_entry' id='search-input' placeholder='Start typing then hit enter to search'>");
			out.println("								<span><a href='search.jsp'>Advanced search</a></span>");
			out.println("								</form>");
			out.println("							</li>");
			out.println("							<li>");
			out.println("								<a href='#' class='hide-search'><i class='fa fa-close'></i></a>");
			out.println("							</li>");
			out.println("						</ul>");
			out.println("					</div>");
			out.println("				</div>");
			out.println("				<div class='navicon'>");
			out.println("					<a class='nav-toggle' href='#'><span></span></a>");
			out.println("				</div>");
			out.println("			</div>");
			out.println("		</div>");
			out.println("	</div>");

			out.println("	<!--Main section-->");
			out.println("	<section class='main' id='product page'>");
			out.println("		<div class='container-fluid'>");
			out.println("			<div class='row'>");
			out.println("				<div class='col-md-6 no-padding carousel js-flickity'>");
			out.println("					<div class='carousel-cell' style='background-image: url(img/product-1.jpg);'>");
			out.println("");
			out.println("						</div>");
			out.println("					");
			out.println("					<div class='carousel-cell' style='background-image: url(img/product-2.jpg);'>");
			out.println("						");
			out.println("					</div>");
			out.println("					<div class='carousel-cell' style='background-image: url(img/product-3.jpg);'>");
			out.println("						");
			out.println("					</div>");
			out.println("				</div>");
			out.println("				<div class='col-md-6'>");
			out.println("					<div class='row'>");
			out.println("						 <div class='col-md-6'>");
			out.println("							<p><a href='index.jsp'>Home ></a> ");
			out.println("							<a href='ViewByCategory?cat_id="+product.getCategory().getId()+"'>"+product.getCategory().getName() +" ></a> ");
			out.println("							<a href='#'>"+product.getName()+"</a></p>");
			out.println("						</div>");
			out.println("					</div>");
			out.println("					<div class='row'>");
			out.println("						<div class='col-md-12'>");
			out.println("							<h1>"+product.getName()+"</h1>");
			out.println("						</div>");
			out.println("					</div>");
			out.println("					<div class='row'>");
			out.println("						<div class='col-sm-6'>");
			out.println("							<h2 class='price'>"+price+"<em> €</em> </h2><small>per piece</small>");
			out.println("						</div>");
			out.println("						<div class='col-sm-3'>");
			out.println("						</div>");
			Double avgRating = null;
			try {
			avgRating = pdao.getAverageRatings(product);
			} catch (Exception e) {
				out.println("						<div class='col-sm-3'>");
				out.println("							<span><i class='fa fa-star'></i> no ratings found &emsp;</span>");
				out.println("						</div>");
			}
			if (avgRating != null){
			out.println("						<div class='col-sm-3'>");
			out.println("							<span><i class='fa fa-star'></i>" +avgRating+"&emsp;</span>");
			out.println("						</div>");
			}
			out.println("					</div>");
			out.println("					<div class='row'>");
			out.println("						<div class='col-sm-12'>");
			out.println("							<hr>");
			out.println("						</div>");
			out.println("					</div>");
			if (userType==null || (!userType.equals("vendor"))) {
				out.println("					<div class='row '>");
				out.println("						<form name='orderForm' method='post' action='orderParam.jsp'>");
				out.println("							<div class= 'col-sm-2'>");
				out.println("								<input name='qrange' placeholder='Qty' maxlength='3' min='1' value='1' class='form-control' type='number'>");
				out.println("							</div>");
				out.println("							<div class= 'col-sm-2'>");
				out.println("								<button type='submit' class='btn btn-default price'>Place order</button>");
				out.println("							</div>	");
				out.println("							<div class= 'col-sm-8'>");
				out.println("							</div>	");
				out.println("						</form>");
				out.println("					</div> ");
			}
			out.println("					<div class='row'>");
			out.println("						<div class='col-sm-12'>");
			out.println("							<hr>");
			out.println("						</div>");
			out.println("					</div>");
			out.println("					<div class='row'>");
			out.println("						<div class='col-sm-12'>");
			out.println("							<ul>");
			out.println("								<li><h3> This Item is final on sale and therefore <em>non returnable.</em><a><i class='fa fa-question'></i></a></h3></li>");
			out.println("								<li><h3>Estimated Delivery Time: <a>Fri 29th of December</a></h3></li>");
			out.println("							</ul>");
			out.println("						</div>");
			out.println("					</div>");
			out.println("					<div class='row'>");
			out.println("						<div class='col-sm-12'>");
			out.println("							<hr>");
			out.println("						</div>");
			out.println("					</div>");
			out.println("					<div class='row'>");
			out.println("						<div class='col-sm-3'>");
			out.println("							<h5>Description:</h5>");
			out.println("						</div>");
			out.println("						<div class='col-sm-6'>");
			out.println("							<ul>");
			out.println("								<li><p>"+product.getDescription() +"</p></li>");
			out.println("							</ul>");
			out.println("						</div>");
			out.println("						<div class='col-sm-3'>");
			out.println("						</div>");

			out.println("					</div>");
			out.println("					<div class='row'>");
			out.println("						<div class='col-sm-12'>");
			out.println("							<hr>");
			out.println("						</div>");
			out.println("					</div>");
			out.println("		<div class='row'>");
			out.println("			<div class='col-sm-3' >");
			out.println("				<h5> Rate this product: </h5>");
			out.println("			</div>");
			out.println("			<div class='col-sm-6' >");
			out.println("				<form name='ratingForm' method='post' action='ratingSubmit.jsp'>");

			double rating = 0;
			if (avgRating != null) {
				rating = avgRating;
			}
			out.println("					<input id='input-21b' name='input-21b'  value='"+ rating +"' type='text' style='colour: #5BC9C5' class='rating' data-min=0 data-max=5 data-step=0.1 data-size='sm'");
			out.println("					  	 required title=''>");
			out.println("					<input id='comment' name='comment'  type='hidden' value='comment' >");
			out.println("					<input id='comment' name='product'  type='hidden' value='"+product.getId()+"' >");

			out.println("					<button type='submit' class='btn btn-default price'>Submit</button>");

			out.println("					<div class='clearfix'></div>");
			out.println("				</form>");
			out.println("			</div>");
			out.println("			<div class='col-sm-3' >");
			out.println("			</div>");
			out.println("		</div>");

			if(request.getAttribute("message") != null) {
				out.println("			");
				out.println("				<div class='row is-centered'>");
				out.println("					<div class='col-sm-12 text-center'>");
				out.println("						<p class='wp1'>"+ (String)request.getAttribute("message") +"</p>");
				out.println("					</div>");
				out.println("				</div>");
				out.println("				<br><br><br>");
			}
			out.println("		<script>");
			out.println("        jQuery(document).ready(function () {");
			out.println("            $('#input-21f').rating({");
			out.println("                starCaptions: function (val) {");
			out.println("                    if (val < 3) {");
			out.println("                        return val;");
			out.println("                    } else {");
			out.println("                        return 'high';");
			out.println("                    }");
			out.println("                },");
			out.println("                starCaptionClasses: function (val) {");
			out.println("                    if (val < 3) {");
			out.println("                        return 'label ';");
			out.println("                    } else {");
			out.println("                        return 'label';");
			out.println("                    }");
			out.println("                },");
			out.println("                hoverOnClear: false");
			out.println("            });");
			out.println("            var $inp = $('#rating-input');");
			out.println("");
			out.println("            $inp.rating({");
			out.println("                min: 0,");
			out.println("                max: 5,");
			out.println("                step: 1,");
			out.println("                size: 'lg',");
			out.println("                showClear: false");
			out.println("            });");
			out.println("");
			out.println("            $('#btn-rating-input').on('click', function () {");
			out.println("                $inp.rating('refresh', {");
			out.println("                    showClear: true,");
			out.println("                    disabled: !$inp.attr('disabled')");
			out.println("                });");
			out.println("            });");
			out.println("");
			out.println("");
			out.println("            $('.btn-danger').on('click', function () {");
			out.println("                $('#kartik').rating('destroy');");
			out.println("            });");
			out.println("");
			out.println("            $('.btn-success').on('click', function () {");
			out.println("                $('#kartik').rating('create');");
			out.println("            });");
			out.println("");
			out.println("            $inp.on('rating.change', function () {");
			out.println("                alert($('#rating-input').val());");
			out.println("            });");
			out.println("");
			out.println("");
			out.println("            $('.rb-rating').rating({");
			out.println("                'showCaption': true,");
			out.println("                'stars': '3',");
			out.println("                'min': '0',");
			out.println("                'max': '3',");
			out.println("                'step': '1',");
			out.println("                'size': 'xs',");
			out.println("                'starCaptions': {0: 'status:nix', 1: 'status:wackelt', 2: 'status:geht', 3: 'status:laeuft'}");
			out.println("            });");
			out.println("            $('#input-21c').rating({");
			out.println("                min: 0, max: 8, step: 0.5, size: 'xl', stars: '8'");
			out.println("            });");
			out.println("        });");
			out.println("    </script>");
			out.println("					<div class='row'>");
			out.println("						<div class='col-sm-12'>");
			out.println("							<hr>");
			out.println("						</div>");
			out.println("					</div>");
			out.println("		<div class='row'>");
			out.println("			<div class='col-md-2'>");
			out.println("			</div>");
			out.println("			<div class='col-md-4'>");
			out.println("				<h5><small>Price and availability subject to change.</small></h5>");
			out.println("			</div>");
			out.println("		</div>");
			out.println("	</section>");

			out.println("	<!-- SECTION: Reccomended -->");
			out.println("	<section class='latest-articles has-padding alternate-bg' id='articles'>");
			out.println("		<div class='container'>");
			out.println("			<div class='row'>");
			out.println("				<div class='col-md-12 col-sm-12'>");
			out.println("					<h4>Best rated in Category: <small>"+ category.getName() +"</small></h4>");
			out.println("				</div>");
			out.println("			</div>");

			List<Product> bestProducts = pdao.getThreeBest(category);
			int counter = 0;
			int rowcheck = 0;
			int div = (bestProducts.size()%3);
			if ( bestProducts.size() == 0){
			out.println("<h3>No products found</h3>");
			}
			for (Product cproduct : bestProducts) {
				counter++;
				Double avgRating2 = null;
				if (counter == 1 && rowcheck > 0) {
					out.println("			<div class='row has-top-margin'>");
					out.println("				<div class='col-md-4'>");
					out.println("					<article class='article-post'>");
					out.println("						<a href='ViewProduct?prod_id="+cproduct.getId()+"'>");
					out.println("							<div class='article-image has-overlay' style='background-image: url(img/article-01.jpg)'>");
					out.println("							</div>");
					out.println("							<figure>");
					out.println("								<figcaption>");
					out.println("									<h2>"+cproduct.getName()+"</h2>");
					out.println("									<p><em>Product Description:</em> "+cproduct.getDescription()+"</p>");
					out.println("								</figcaption>");
					out.println("							</figure>");
					out.println("						</a>");
					out.println("						<ul class='article-footer'>");
					out.println("							<li class='article-category'>");
					out.println("								<a href='#'>"+category.getName()+"</a>");
					out.println("							</li>");
					out.println("							");
					out.println("							<li class='article-comments'>");
					try {
						avgRating2 = pdao.getAverageRatings(cproduct);
						} catch (Exception e) {
							out.println("								<span><i class='fa fa-star'></i>no ratings found </span>");
						}
						if (avgRating != null){
							out.println("								<span><i class='fa fa-star'></i>"+pdao.getAverageRatings(cproduct)+"&emsp;</span>");
						}
					avgRating2 = null;
					out.println("							</li>");
					out.println("						</ul>");
					out.println("					</article>");
					out.println("				</div>");
					if (div == 1) {
						out.println("		</div>");
					}

				}else if (counter == 1) {
					out.println("			<div class='row'>");
					out.println("				<div class='col-md-4'>");
					out.println("					<article class='article-post'>");
					out.println("						<a href='ViewProduct?prod_id="+cproduct.getId()+"'>");
					out.println("							<div class='article-image has-overlay' style='background-image: url(img/article-01.jpg)'>");
					out.println("							</div>");
					out.println("							<figure>");
					out.println("								<figcaption>");
					out.println("									<h2>"+cproduct.getName()+"</h2>");
					out.println("									<p><em>Product Description:</em> "+cproduct.getDescription()+"</p>");
					out.println("								</figcaption>");
					out.println("							</figure>");
					out.println("						</a>");
					out.println("						<ul class='article-footer'>");
					out.println("							<li class='article-category'>");
					out.println("								<a href='#'>"+category.getName()+"</a>");
					out.println("							</li>");
					out.println("							");
					out.println("							<li class='article-comments'>");
					try {
						avgRating2 = pdao.getAverageRatings(cproduct);
						} catch (Exception e) {
							out.println("								<span><i class='fa fa-star'></i>no ratings found </span>");
						}
						if (avgRating != null){
							out.println("								<span><i class='fa fa-star'></i>"+pdao.getAverageRatings(cproduct)+"&emsp;</span>");
						}
					avgRating2 = null;
					out.println("							</li>");
					out.println("						</ul>");
					out.println("					</article>");
					out.println("				</div>");
					if (div == 1) {
						out.println("		</div>");
					}

				} else if (counter == 2){
					out.println("				<div class='col-md-4'>");
					out.println("					<article class='article-post'>");
					out.println("						<a href='ViewProduct?prod_id="+cproduct.getId()+"'>");
					out.println("							<div class='article-image has-overlay' style='background-image: url(img/article-01.jpg)'>");
					out.println("							</div>");
					out.println("							<figure>");
					out.println("								<figcaption>");
					out.println("									<h2>"+cproduct.getName()+"</h2>");
					out.println("									<p><em>Product Description:</em> "+cproduct.getDescription()+"</p>");
					out.println("								</figcaption>");
					out.println("							</figure>");
					out.println("						</a>");
					out.println("						<ul class='article-footer'>");
					out.println("							<li class='article-category'>");
					out.println("								<a href='#'>"+category.getName()+"</a>");
					out.println("							</li>");
					out.println("							");
					out.println("							<li class='article-comments'>");
					try {
						avgRating2 = pdao.getAverageRatings(cproduct);
						} catch (Exception e) {
							out.println("								<span><i class='fa fa-star'></i>no ratings found </span>");
						}
						if (avgRating != null){
							out.println("								<span><i class='fa fa-star'></i>"+pdao.getAverageRatings(cproduct)+"&emsp;</span>");
						}
					avgRating2 = null;
					out.println("							</li>");
					out.println("						</ul>");
					out.println("					</article>");
					out.println("				</div>");
					if (div == 2) {
						out.println("		</div>");
					}

				} else if (counter == 3) {
					out.println("				<div class='col-md-4'>");
					out.println("					<article class='article-post'>");
					out.println("						<a href='ViewProduct?prod_id="+cproduct.getId()+"'>");
					out.println("							<div class='article-image has-overlay' style='background-image: url(img/article-01.jpg)'>");
					out.println("							</div>");
					out.println("							<figure>");
					out.println("								<figcaption>");
					out.println("									<h2>"+cproduct.getName()+"</h2>");
					out.println("									<p><em>Product Description:</em> "+cproduct.getDescription()+"</p>");
					out.println("								</figcaption>");
					out.println("							</figure>");
					out.println("						</a>");
					out.println("						<ul class='article-footer'>");
					out.println("							<li class='article-category'>");
					out.println("								<a href='#'>"+category.getName()+"</a>");
					out.println("							</li>");
					out.println("							");
					out.println("							<li class='article-comments'>");
					try {
						avgRating2 = pdao.getAverageRatings(cproduct);
						} catch (Exception e) {
							out.println("								<span><i class='fa fa-star'></i>no ratings found </span>");
						}
						if (avgRating != null){
							out.println("								<span><i class='fa fa-star'></i>"+pdao.getAverageRatings(cproduct)+"&emsp;</span>");
						}
					avgRating2 = null;
					out.println("							</li>");
					out.println("						</ul>");
					out.println("					</article>");
					out.println("				</div>");
					out.println("			</div>");
					counter = 0;
					rowcheck++;
				}
			}
			out.println("				</div>");
			out.println("			</section>");
			out.println("	<!-- END SECTION: Reccomended -->");

			out.println("	<!-- SECTION: Specs -->");
			out.println("	<section class='freebies has-padding' id='freebies'>");
			out.println("		<div class='container freebies-intro'>");
			out.println("			<div class='row'>");
			out.println("				<div class='col-md-12'>");
			out.println("					<h4>Product Information <small>for aesthetic purposes only </small></h4>");
			out.println("				</div>");
			out.println("			</div>");
			out.println("			<div class='row'>");
			out.println("				<div class='col-md-6 content-left'>");
			out.println("					<h5>Technical Specifications</h5><hr>");
			out.println("					<table class='table'>");
			out.println("						<tbody>");
			out.println("							<tr>");
			out.println("								<td>Brand Name</td>");
			out.println("								<td>MakerBot</td>");
			out.println("							</tr>");
			out.println("							<tr>");
			out.println("								<td>Item Weight  </td>");
			out.println("								<td>52.27 Kilos</td>");
			out.println("							</tr>");
			out.println("							<tr>");
			out.println("								<td>Product Dimensions</td>");
			out.println("								<td>33.9 x 22.2 x 19.4 inches</td>");
			out.println("							</tr>");
			out.println("							<tr>");
			out.println("								<td>Item model number </td>");
			out.println("								<td>MP05950</td>");
			out.println("							</tr>");
			out.println("							<tr>");
			out.println("								<td>Material Type </td>");
			out.println("								<td>PLA</td>");
			out.println("							</tr>");
			out.println("							<tr>");
			out.println("								<td>Manufacturer Part Number </td>");
			out.println("								<td>MP05950</td>");
			out.println("							</tr>");
			out.println("						</tbody>");
			out.println("					</table>");
			out.println("				</div>");
			out.println("				<div class='col-md-6 content-right'>");
			out.println("					<h5>Warranty & Support</h5><hr><p>Manufacturer's warranty can be requested from customer service.Click <a>here</a> to make a request to customer service.</p>");
			out.println("				</div>");
			out.println("			</div>");
			out.println("		</div>");
			out.println("	</section>");
			out.println("	<!-- END SECTION: Specs -->");


			if (session.getAttribute("user-object") == null){
				out.println("<section class='get-started has-padding text-center' id='get-started'>");
				out.println("	<div class='container'>");
				out.println("		<div class='row'>");
				out.println("			<div class='col-md-12 wp4 animated fadeInUp'>");
				out.println("				<h2>Join Open Commerce <a href='http://tympanus.net/codrops/?p=26570'>NOW</a>, for free.</h2>");
				out.println("				<a href='register.jsp' class='btn secondary-white'>Get started</a>");
				out.println("			</div>");
				out.println("		</div>");
				out.println("	</div>");
				out.println("</section>");

			}
			out.println("	<!-- SECTION: Footer -->");
			out.println("	<footer class='has-padding footer-bg'>");
			out.println("		<div class='container'>");
			out.println("			<div class='row'>");
			out.println("				<div class='col-md-4 footer-branding wp5'>");
			out.println("					<img class='footer-branding-logo' src='img/synthetica-logo.png' alt='Synthetica freebie html5 css3 template logo'>");
			out.println("				</div>");
			out.println("				<div class='col-md-4 footer-branding wp5'>");
			out.println("					<img class='footer-branding-logo' src='img/ismgroup42.png' alt='ismlogo'>");
			out.println("				</div>");
			out.println("				<div class='col-md-4 footer-branding wp5'>");
			out.println("					<img class='footer-branding-logo' src='img/DMST.png' alt='dmstl'>");
			out.println("				</div>");
			out.println("			</div>");
			out.println("			<div class='row'>");
			out.println("				<div class='col-md-4 footer-branding wp5 animated fadeIn'>");
			out.println("					<p>Opencommerce.gr was created using the theme Synthetica, generously provided by <a href='http://peterfinlan.com/'><em>Peter Finlan</em></a> for <a href='https://tympanus.net/codrops/'><em>codrops</em></a>. Back-end coding and modification by <a href='#'><em>ismGroup42</em></a>.</p>");
			out.println("				</div>");
			out.println("			</div>");
			out.println("			<div class='row'>");
			out.println("				<div class='col-md-12 footer-nav'>");
			out.println("					<ul class='footer-primary-nav'>");
			out.println("						<li><a href='index.jsp'>Home</a></li>");
			out.println("						<li><a href='browse.jsp'>Browse</a></li>");
			out.println("						<li><a href='dashboard.jsp'>Dashboard</a></li>");
			if (session.getAttribute("user-object") != null) {
				out.println("						<li><a href='logout.jsp'>Logout</a></li>");
			} else {
				out.println("						<li><a href='login.jsp'>Login</a></li>");
			}
			out.println("					</ul>");
			out.println("					<ul class='footer-share'>");
			out.println("						<li><a href='http://tympanus.net/codrops/licensing/'>Licence</a></li>");
			out.println("						<li><a href='#' class='share-trigger'><i class='fa fa-share'></i>Share</a></li>");
			out.println("					</ul>");
			out.println("					<div class='share-dropdown'>");
			out.println("						<ul>");
			out.println("							<li><a href='#' class='share-twitter'><i class='fa fa-twitter'></i></a></li>");
			out.println("							<li><a href='#' class='share-facebook'><i class='fa fa-facebook'></i></a></li>");
			out.println("							<li><a href='#' class='share-linkedin'><i class='fa fa-linkedin'></i></a></li>");
			out.println("						</ul>");
			out.println("					</div>");
			out.println("					<ul class='footer-secondary-nav'>");
			out.println("						<li><p>ï¿½ Copyright <a href='#'><em> ismGroup42</em></a>. All rights reserved | <a href='#'><em>Terms Of Use</em></a> | <a href='#'><em>Contact</em></a></p></li>");
			out.println("					</ul>");
			out.println("				</div>");
			out.println("			</div>");
			out.println("		</div>");
			out.println("	</footer>");
			out.println("	<!-- END SECTION: Footer -->");
			out.println("	<!-- JS CDNs -->");
			out.println("	<script src='http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js'></script>");
			out.println("	<script src='http://ajax.googleapis.com/ajax/libs/jqueryui/1.11.0/jquery-ui.min.js'></script>");
			out.println("	<script src='http://vjs.zencdn.net/5.4.6/video.min.js'></script>");
			out.println("	<!-- jQuery local fallback -->");
			out.println("	<script>");
			out.println("	window.jQuery || document.write('<script src='js/min/jquery-1.11.2.min.js'><//script>')");
			out.println("	</script>");
			out.println("	<!-- JS Locals -->");
			out.println("	<script src='js/min/bootstrap.min.js'></script>");
			out.println("	<script src='js/min/modernizr-2.8.3-respond-1.4.2.min.js'></script>");
			out.println("	<script src='js/min/retina.min.js'></script>");
			out.println("	<script src='js/min/jquery.waypoints.min.js'></script>");
			out.println("	<script src='js/min/flickity.pkgd.min.js'></script>");
			out.println("	<script src='js/min/scripts-min.js'></script>");
			out.println("");
			out.println("</body>");
			out.println("</html>");


		}catch (Exception e) {
			e.printStackTrace();
			out.println("	<div class='container'>");
			out.println("		<div class='alert alert-danger' role='alert'>");
			out.println("			<p class='text-center'> Error : " + e.getMessage()+"</p>");
			out.println("		</div>");
			out.println("	</div>");
			out.println("	<!-- SECTION: Footer -->");
			out.println("	<footer class='has-padding footer-bg'>");
			out.println("		<div class='container'>");
			out.println("			<div class='row'>");
			out.println("				<div class='col-md-4 footer-branding wp5'>");
			out.println("					<img class='footer-branding-logo' src='img/synthetica-logo.png' alt='Synthetica freebie html5 css3 template logo'>");
			out.println("				</div>");
			out.println("				<div class='col-md-4 footer-branding wp5'>");
			out.println("					<img class='footer-branding-logo' src='img/ismgroup42.png' alt='ismlogo'>");
			out.println("				</div>");
			out.println("				<div class='col-md-4 footer-branding wp5'>");
			out.println("					<img class='footer-branding-logo' src='img/DMST.png' alt='dmstl'>");
			out.println("				</div>");
			out.println("			</div>");
			out.println("			<div class='row'>");
			out.println("				<div class='col-md-4 footer-branding wp5 animated fadeIn'>");
			out.println("					<p>Opencommerce.gr was created using the theme Synthetica, generously provided by <a href='http://peterfinlan.com/'><em>Peter Finlan</em></a> for <a href='https://tympanus.net/codrops/'><em>codrops</em></a>. Back-end coding and modification by <a href='#'><em>ismGroup42</em></a>.</p>");
			out.println("				</div>");
			out.println("			</div>");
			out.println("			<div class='row'>");
			out.println("				<div class='col-md-12 footer-nav'>");
			out.println("					<ul class='footer-primary-nav'>");
			out.println("						<li><a href='index.jsp'>Home</a></li>");
			out.println("						<li><a href='browse.jsp'>Browse</a></li>");
			out.println("						<li><a href='dashboard.jsp'>Dashboard</a></li>");
			if (session.getAttribute("user-object") != null) {
				out.println("						<li><a href='logout.jsp'>Logout</a></li>");
			} else {
				out.println("						<li><a href='login.jsp'>Login</a></li>");
			}
			out.println("					</ul>");
			out.println("					<ul class='footer-share'>");
			out.println("						<li><a href='http://tympanus.net/codrops/licensing/'>Licence</a></li>");
			out.println("						<li><a href='#' class='share-trigger'><i class='fa fa-share'></i>Share</a></li>");
			out.println("					</ul>");
			out.println("					<div class='share-dropdown'>");
			out.println("						<ul>");
			out.println("							<li><a href='#' class='share-twitter'><i class='fa fa-twitter'></i></a></li>");
			out.println("							<li><a href='#' class='share-facebook'><i class='fa fa-facebook'></i></a></li>");
			out.println("							<li><a href='#' class='share-linkedin'><i class='fa fa-linkedin'></i></a></li>");
			out.println("						</ul>");
			out.println("					</div>");
			out.println("					<ul class='footer-secondary-nav'>");
			out.println("						<li><p>© Copyright <a href='#'><em> ismGroup42</em></a>. All rights reserved | <a href='#'><em>Terms Of Use</em></a> | <a href='#'><em>Contact</em></a></p></li>");
			out.println("					</ul>");
			out.println("				</div>");
			out.println("			</div>");
			out.println("		</div>");
			out.println("	</footer>");
			out.println("	<!-- END SECTION: Footer -->");
			out.println("	<!-- JS CDNs -->");
			out.println("	<script src='http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js'></script>");
			out.println("	<script src='http://ajax.googleapis.com/ajax/libs/jqueryui/1.11.0/jquery-ui.min.js'></script>");
			out.println("	<script src='http://vjs.zencdn.net/5.4.6/video.min.js'></script>");
			out.println("	<!-- jQuery local fallback -->");
			out.println("	<script>");
			out.println("	window.jQuery || document.write('<script src='js/min/jquery-1.11.2.min.js'><//script>')");
			out.println("	</script>");
			out.println("	<!-- JS Locals -->");
			out.println("	<script src='js/min/bootstrap.min.js'></script>");
			out.println("	<script src='js/min/modernizr-2.8.3-respond-1.4.2.min.js'></script>");
			out.println("	<script src='js/min/retina.min.js'></script>");
			out.println("	<script src='js/min/jquery.waypoints.min.js'></script>");
			out.println("	<script src='js/min/flickity.pkgd.min.js'></script>");
			out.println("	<script src='js/min/scripts-min.js'></script>");
			out.println("");
			out.println("</body>");
			out.println("</html>");
		}
	}

	public void doGet(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        doPost(request, response);
	}
}
